/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadulp.vistas;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juan_
 */
public class menuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuPrincipal
     */
    public menuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAlumno = new javax.swing.JMenu();
        formularioAlumno = new javax.swing.JMenuItem();
        menuMateria = new javax.swing.JMenu();
        formMateria = new javax.swing.JMenuItem();
        menuAdministracion = new javax.swing.JMenu();
        formInscripcion = new javax.swing.JMenuItem();
        menuNotas = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        listAlumnosxMateria = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1093, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        menuAlumno.setText("Alumno");

        formularioAlumno.setText("Formulario de Alumno");
        formularioAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formularioAlumnoActionPerformed(evt);
            }
        });
        menuAlumno.add(formularioAlumno);

        jMenuBar1.add(menuAlumno);

        menuMateria.setText("Materia");

        formMateria.setText("Formulario de materia");
        formMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formMateriaActionPerformed(evt);
            }
        });
        menuMateria.add(formMateria);

        jMenuBar1.add(menuMateria);

        menuAdministracion.setText("Administración");

        formInscripcion.setText("Manejo de inscripciones");
        formInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formInscripcionActionPerformed(evt);
            }
        });
        menuAdministracion.add(formInscripcion);

        menuNotas.setText("Manipulación de notas");
        menuNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNotasActionPerformed(evt);
            }
        });
        menuAdministracion.add(menuNotas);

        jMenuBar1.add(menuAdministracion);

        menuConsultas.setText("Consultas");

        listAlumnosxMateria.setText("Alumnos por materia");
        listAlumnosxMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAlumnosxMateriaActionPerformed(evt);
            }
        });
        menuConsultas.add(listAlumnosxMateria);

        jMenuBar1.add(menuConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formInscripcionActionPerformed
        limpiar();
        FormularioDeInscripcion fdi = new FormularioDeInscripcion();
        fdi.setVisible(true);
        escritorio.add(fdi);
        escritorio.moveToFront(fdi);
    }//GEN-LAST:event_formInscripcionActionPerformed

    private void formularioAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formularioAlumnoActionPerformed
        limpiar();
        Alumno al = new Alumno();
        al.setVisible(true);
        escritorio.add(al);
        escritorio.moveToFront(al);
    }//GEN-LAST:event_formularioAlumnoActionPerformed

    private void formMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formMateriaActionPerformed
        limpiar();
        MateriaView mat = new MateriaView();
        mat.setVisible(true);
        escritorio.add(mat);
        escritorio.moveToFront(mat);
    }//GEN-LAST:event_formMateriaActionPerformed

    private void menuNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNotasActionPerformed
        limpiar();
        CargaDeNotas cdn = new CargaDeNotas();
        cdn.setVisible(true);
        escritorio.add(cdn);
        escritorio.moveToFront(cdn);
    }//GEN-LAST:event_menuNotasActionPerformed

    private void listAlumnosxMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAlumnosxMateriaActionPerformed
        limpiar();
        ListadoAlumnosPorMateria laxm  = new ListadoAlumnosPorMateria();
        laxm.setVisible(true);
        escritorio.add(laxm);
        escritorio.moveToFront(laxm);
    }//GEN-LAST:event_listAlumnosxMateriaActionPerformed

    private void limpiar(){
        escritorio.removeAll();
        escritorio.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem formInscripcion;
    private javax.swing.JMenuItem formMateria;
    private javax.swing.JMenuItem formularioAlumno;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem listAlumnosxMateria;
    private javax.swing.JMenu menuAdministracion;
    private javax.swing.JMenu menuAlumno;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuMateria;
    private javax.swing.JMenuItem menuNotas;
    // End of variables declaration//GEN-END:variables
}
